blog/Post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired,Length


class NewPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max= 100)])
    content= TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')
                

blog/Main/routes.py
from flask import Blueprint , render_template, request
from blog.models import Post


Main = Blueprint('Main', __name__) 



@Main.route('/')
def home():
    page = request.args.get('page', 1 ,type=int) #Gets the type of page requested from the client and specifies nthe default number to 1 and if the client requests a page that is not an integer it throws an error
    post = Post.query.order_by(Post.date_posted.desc()).paginate(page=page ,per_page=2) #accounts for the number of post per_page
    return render_template('home.html', title ="home" , posts= post)



@Main.route('/about')
def about():
    return render_template('about.html', title ="about" )

blog/Post/routes.py
from flask import (Blueprint , render_template ,flash , redirect, request,
url_for,abort )

from blog import db
from flask_login import current_user , login_required
from blog.models import Post
from blog.Post.forms import NewPostForm


Posts = Blueprint('post', __name__)


@Posts.route('/post/new', methods= ["GET","POST"])
def new_post():
    form= NewPostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('New Post Added','success')
        return redirect(url_for('Main.home'))
               

    return render_template('New.html', title='New Post', form=form, legend='New Post')




@Posts.route('/post/<int:post_id>')
def post(post_id):
    post= Post.query.get_or_404(post_id)

    return render_template('post.html', title=post.title,post=post)





@Posts.route('/post/<int:post_id>/edit', methods=['GET','POST'])
@login_required
def edit_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = NewPostForm()
    
    if  request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content

    else:
        if form.validate_on_submit:
            post.title = form.title.data
        post.content= form.content.data
        db.session.commit()
        flash('Post Successfully Updated', 'success')
        return redirect(url_for('post.post',post_id=post.id))

    return render_template('New.html', title='Edit Post', form=form ,legend='Edit Post')
    


@Posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post successfully deleted!','success')
    return redirect(url_for('Main.home'))








    

blog/Users/routes.py
from flask import Blueprint ,render_template, url_for, flash, redirect,request, abort
from flask_login import login_user, current_user, logout_user, login_required
from blog  import app, bcrypt, db
from blog.models  import User, Post
from blog.Users.forms import RegistrationForm, LoginForm,UpdateAccountForm, RequestResetForm, ResetPasswordForm
from blog.Users.utils import save_picture, send_reset_email
users = Blueprint('users',__name__)



@users.route('/register', methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('Main.home'))
    form  = RegistrationForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pwd)
        db.session.add(user)
        #db.session.rollback()
        db.session.commit()
        flash('Account was successfully created! You can now log in', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html',title='registration form' , form = form)




@users.route('/login', methods = ['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Welcome {current_user.username} ','success')
            
            return redirect(next_page) if next_page else redirect(url_for('Main.home'))
            

        else:
            flash(f'Log in unsuccesful, try again', "danger" )
    return render_template('login.html',title='Login |' ,form = form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('Main.home'))




@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data) #saves the updated picture
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data 
        db.session.commit()
        flash('Account Successfully Updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pic/'+ current_user.image_file)
   
    
    return render_template('account.html', title='Account' ,image_file=image_file, form=form)



@users.route('/user/<string:username>')
def user_post(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1 ,type=int) #Gets the type of page requested from the client and specifies nthe default number to 1 and if the client requests a page that is not an integer it throws an error
    post = Post.query.filter_by(author=user)\
    .order_by(Post.date_posted.desc())\
    .paginate(page=page ,per_page=2) #accounts for the number of post per_page
    return render_template('user_post.html', title ="User Post" , posts= post, username=user)




@users.route('/reset_Password/', methods= ["GET","POST"])
def pwd_reset():    
    
    if current_user.is_authenticated:
        return redirect(url_for('Main.home'))
    form= RequestResetForm()
    if request.method == "GET":
            return render_template('RequestPassword.html' , title='Request Password Reset', form=form)
    if form.validate_on_submit:
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions on how to reset your password ', 'info')
        return redirect(url_for('users.login'))
    



@users.route('/reset_Password/<token>', methods= ["GET","POST"])
def reset_token(token):    
    if current_user.is_authenticated:
        return redirect(url_for('Main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('This is an invalid or expired  token', 'warning')
        return redirect(url_for('users.pwd_reset'))
    form= ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pwd
        
        db.session.commit()
        flash('Password has been updated successfully! You can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset.html', title='Reset Password', form=form)
    

blog/templates/New.html
{%extends "layout.html"%}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 h3 pt-3 pb-3 mb-3 font-weight-normal">
                 {{legend}}
            </legend>
           
            <div class="form-group">
                 
                 {{form.title.label(class="form-control-label")}}
                {% if form.title.errors %}
                {{form.title(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {%  for error in form.title.errors %}
                        <span>{{ error }}</span>
                     {% endfor %}

                </div>
                {% else %}
                    {{form.title(class="form-control form-control-lg")}}
                 {% endif %}
             </div>
             <div class="form-group">
                     {{form.content.label(class="form-control-label")}}
                    
                     {% if form.content.errors %}
                     {{form.content(class="form-control form-control-lg is-invalid")}}
                     <div class="invalid-feedback">
                         {%  for error in form.content.errors %}
                             <span>{{ error }}</span>
                          {% endfor %}
  
                     </div>
                     {% else %}
                         {{form.content(class="form-control form-control-lg")}}
                     {% endif %}
  
             </div >
            
            
                 
        </fieldset>
        <div class="form-group">
            {{form.submit(class = "btn btn-default  btn-primary")}}
        </div>
    </form>
{% endblock %}

blog/templates/RequestPassword.html
{%extends "layout.html"%}

{% block content %}
<div class="content-size card p-3">
        <form action="" method="POST">
            {{form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 h3 mb-3 font-weight-normal">
                     Request Password Reset
                </legend>
               
                <div class="form-group">
                     
                     {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                    {{form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {%  for error in form.email.errors %}
                            <span>{{ error }}</span>
                         {% endfor %}
 
                    </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                     {% endif %}
                 </div>
                
            </fieldset>
            <div class="form-group">
                {{form.submit(class = "btn btn-default  btn-outline-primary")}}
            </div>
            
        </form>
       
 
    </div>
{% endblock content %}

blog/templates/account.html
{% extends  "layout.html"%}
{% block content %}
<div class="container">

<div class="content-section">
    <div class="media">
        <img src= '{{ image_file }}' alt="" class=" float-left w-25 mb-3 h-50 p-4 account-img">
        <div class="media-body">
            <h2 class="account-heading">{{current_user.username}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
        </div>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {{form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Update Account Info
            </legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {% if form.username.errors %}
                {{form.username(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {%  for error in form.username.errors %}
                        <span>{{ error }}</span>
                     {% endfor %}

                </div>
                {% else %}
                    {{form.username(class="form-control form-control-lg")}}
                 {% endif %}

            </div>
            <div class="form-group">
                 {{form.email.label(class="form-control-label")}}
                 
                {% if form.email.errors %}
                {{form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {%  for error in form.email.errors %}
                        <span>{{ error }}</span>
                     {% endfor %}

                </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}}
                 {% endif %}
             </div>
             <div class="form-group">
                {{form.picture.label()}}
                {{ form.picture(class="form-control-file")}}

                {% if form.picture.errors %}
                    {% for error in form.picture.errors%}
                            <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                
            
                 
        </fieldset>
        <div class="form-group">
            {{form.submit(class = "btn btn-default  btn-primary")}}
        </div>
       </form>

    
</div>
</div>
{% endblock %}

blog/templates/home.html
{%extends "layout.html"%}
{% block content%}
    {%for post in posts.items %}
       <article class="container card mb-3 p-3">
    
           <div class="media-body">
                <img src= "{{url_for('static', filename='profile_pic/'+ post.author.image_file)}}" class= " float-left w-25 h-25 mb-3 pt-3 mr-3" alt="">
           <h6><a  href = "{{ url_for('users.user_post', username=post.author.username) }}" class= ' ml-3 mr-3 float-right'>{{post.author.username}}</a></h6>
           <small class="text-muted float-right">{{post.date_posted.strftime('%Y-%m-%d')}}</small>&nbsp;
           <h1><a href="{{url_for('post.post', post_id=post.id )}}"> {{post.title}} </a></h1>
           <hr>
           </div>
           <p class= 'article-content'>
               {{post.content}}
           </p>
           
        </article>
    {%endfor%}
    {%for page_num in posts.iter_pages(left_edge=1, right_edge=2 , left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a href="{{url_for('Main.home',page=page_num)}}" class="btn  btn-default mb-4 btn-info">{{page_num}}</a>
            {%else%}
              <a href="{{url_for('Main.home',page=page_num)}}" class="btn btn-default   mb-4  btn-outline-info">{{page_num}}</a>
            {%endif%}
            {%else%}
                ...
        {% endif %}
    {%endfor%}
{%endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type ="text/css" href= "{{url_for('static',filename='main.css')}}">
    <title>{{title}}</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary text-dark">
                <a class="navbar-brand" class="display-1" href="#">Aproko</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
          
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{{ url_for('Main.home')}}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{url_for('Main.about')}}">About</a>
                    </li>
                  </ul>
                  <ul class="navbar-nav mr-auto">
                      {% if current_user.is_authenticated%}
                             <li class="nav-item">
                        <a href="{{ url_for('post.new_post')}}"class="nav-link">New Post</a>
                            </li>
                             <li class="nav-item">
                              <a href="{{ url_for('users.account')}}"class="nav-link">Account</a>
                             </li>  
                                <li class="nav-item">
                              <a href="{{ url_for('users.logout')}}"class="nav-link">Logout</a>
                          </li>
                      {% else %}
                        <li class="nav-item">
                            <a href="{{ url_for('users.login')}}" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url_for('users.register')}}" class="nav-link">Register</a>
                        </li>
                        {%endif%}
                    </ul>
                  </div>
                 
                  </nav>
                  </header>
                  <br>
                  <br>
                  <br>
              
             <main class="container main">
                 <div class="row">
                     <div class="col-md-8">
                         {% with messages = get_flashed_messages(with_categories=true )%}
                            {% if messages %}
                                {% for category,message in messages %}
                                   <div class="alert alert-{{ category }}">
                                       {{ message }}
                                   </div>
                                {% endfor %}
                            {% endif %}
                         {% endwith %}
                         {% block content %}{% endblock  %}
                     </div>
                    
                 </div>

             </main>
    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>


        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
</body>
</html>

blog/templates/login.html
{%extends "layout.html"%}

{% block content %}
<div class="content-size">
        <form action="" method="POST">
            {{form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 h3 mb-3 font-weight-normal">
                     Login
                </legend>
               
                <div class="form-group">
                     
                     {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                    {{form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {%  for error in form.email.errors %}
                            <span>{{ error }}</span>
                         {% endfor %}
 
                    </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                     {% endif %}
                 </div>
                 <div class="form-group">
                         {{form.password.label(class="form-control-label")}}
                        
                         {% if form.password.errors %}
                         {{form.password(class="form-control form-control-lg is-invalid")}}
                         <div class="invalid-feedback">
                             {%  for error in form.password.errors %}
                                 <span>{{ error }}</span>
                              {% endfor %}
      
                         </div>
                         {% else %}
                             {{form.password(class="form-control form-control-lg")}}
                         {% endif %}
      
                 </div >
                 <div class="form-check">
                     {{form.remember(class="form-check-input ")}}
                     {{form.remember.label(class="form-check-label checkbox mb-3")}}

                 </div>
                
                     
            </fieldset>
            <div class="form-group">
                {{form.submit(class = "btn btn-default  btn-primary")}}
                 <small class="text-muted ml-2"><a href="{{url_for('users.pwd_reset')}}">Forgot password?</a></small>
            </div>
            
        </form>
       <div class="border-top pt-3">
           <small class="text-muted">
               Need an Account? <a  class ='ml-2'href="{{url_for('users.register')}}">Register Here</a>
           </small>
       </div>
 
    </div>
{% endblock content %}

blog/templates/post.html
{%extends "layout.html"%}
{% block content%}
    
       <article class="container card mb-3 p-3">
    
           <div class="media-body">
                
                <img src= "{{url_for('static', filename='profile_pic/'+ post.author.image_file)}}" class= " float-right w-25 h-25 mb-3 pt-3 mr-3 m-2 account-img" alt="">
                
           <div class="pb-3">
                <h2 class='jumbotron float-left ' href="#"> {{post.title}} </h2>
            <a  href="{{url_for('users.user_post', username=post.author.username)}}"class= ' h2  ml-3  mr-3 float-left'>{{post.author.username}}</a>
            <small class=" h4 text-muted float-left ">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
           
           
            <hr class='mb-1'>
           </div>
           </div>
           <p class= 'article-content'>
               {{post.content}}
           </p>
           {% if post.author == current_user %}
           <div class=>
               <a href="{{ url_for('post.edit_post', post_id = post.id)}}" class="btn btn-sm m-1 btn-info">Edit</a>
               <button class="btn btn-danger btn-sm m-1" data-toggle='modal' data-target='#deleteModal'>Delete</button>
           </div>
        {%endif%}
           
        </article>
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Delete Post </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <form action="{{url_for('post.delete_post', post_id=post.id)}}"method = "POST">
                      <input type="submit" value="Delete" class="btn btn-danger">
                  </form>
                </div>
              </div>
            </div>
          </div>
    
{%endblock %}

blog/templates/register.html
{%extends "layout.html"%}
{% block content%}
   <div class="content-size">
       <form action="" method="POST">
           {{form.hidden_tag() }}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">
                   Sign Up Today !
               </legend>
               <div class="form-group">
                   {{form.username.label(class="form-control-label")}}
                   {% if form.username.errors %}
                   {{form.username(class="form-control form-control-lg is-invalid")}}
                   <div class="invalid-feedback">
                       {%  for error in form.username.errors %}
                           <span>{{ error }}</span>
                        {% endfor %}

                   </div>
                   {% else %}
                       {{form.username(class="form-control form-control-lg")}}
                    {% endif %}

               </div>
               <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    
                   {% if form.email.errors %}
                   {{form.email(class="form-control form-control-lg is-invalid")}}
                   <div class="invalid-feedback">
                       {%  for error in form.email.errors %}
                           <span>{{ error }}</span>
                        {% endfor %}

                   </div>
                   {% else %}
                       {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>
                <div class="form-group">
                        
                        {{form.password.label(class="form-control-label")}}
                        {% if form.password.errors %}
                        {{form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {%  for error in form.password.errors %}
                                <span>{{ error }}</span>
                             {% endfor %}
     
                        </div>
                        {% else %}
                            {{form.password(class="form-control form-control-lg")}}
                         {% endif %}
     
                </div >
                <div class="form-group">
                        {{form.confirm_password.label(class="form-control-label")}}
                        
                   {% if form.confirm_password.errors %}
                   {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
                   <div class="invalid-feedback">
                       {%  for error in form.confirm_password.errors %}
                           <span>{{ error }}</span>
                        {% endfor %}

                   </div>
                   {% else %}
                       {{form.confirm_password(class="form-control form-control-lg")}}
                    {% endif %}
     
                </div >
               
                    
           </fieldset>
           <div class="form-group">
               {{form.submit(class = "btn btn-default  btn-primary")}}
           </div>
       </form>
       <div class="border-top pt-3">
           <small class="text-muted">
               Already Have an account? <a class='ml-2' href="{{url_for('users.login')}}">Log in here</a>
           </small>
       </div>

   </div>
{%endblock content %}

blog/templates/reset.html
{%extends "layout.html"%}

{% block content %}
<div class="content-size card">
        <form action="" method="POST">
            {{form.hidden_tag() }}
            <fieldset class="form-group p-3">
                <legend class="border-bottom mb-4 h3 mb-3 font-weight-normal">
                     Request Password Reset
                </legend>
               
                <div class="form-group p-3">
                     
                     {{form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                    {{form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {%  for error in form.password.errors %}
                            <span>{{ error }}</span>
                         {% endfor %}
 
                    </div>
                    {% else %}
                        {{form.password(class="form-control form-control-lg")}}
                     {% endif %}
                 </div>

                 <div class="form-group">
                    {{form.confirm_password.label(class="form-control-label")}}
                    
               {% if form.confirm_password.errors %}
               {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
               <div class="invalid-feedback">
                   {%  for error in form.confirm_password.errors %}
                       <span>{{ error }}</span>
                    {% endfor %}

               </div>
               {% else %}
                   {{form.confirm_password(class="form-control form-control-lg")}}
                {% endif %}
 
            </div >
           
                
            </fieldset>
            <div class="form-group">
                {{form.submit(class = "btn btn-default  btn-outline-info")}}
            </div>
            
        </form>
       
 
    </div>
{% endblock content %}

blog/templates/user_post.html
{%extends "layout.html"%}
{% block content%}
<h1 class="h2">Posts By {{username.username}} ({{posts.total}})</h1>
    {%for post in posts.items %}
       <article class="container card mb-3 p-3">
    
           <div class="media-body">
                <img src= "{{url_for('static', filename='profile_pic/'+ post.author.image_file)}}" class= " float-left w-25 h-25 mb-3 pt-3 mr-3" alt="">
           <h6><a  href = "{{url_for('users.user_post', username=post.author.username)}}" class= ' ml-3 mr-3 float-right'>{{post.author.username}}</a></h6>
           <small class="text-muted float-right">{{post.date_posted.strftime('%Y-%m-%d')}}</small>&nbsp;
           <h1><a href="{{url_for('post.post', post_id=post.id )}}"> {{post.title}} </a></h1>
           <hr>
           </div>
           <p class= 'article-content'>
               {{post.content}}
           </p>
           
        </article>
    {%endfor%}
    {%for page_num in posts.iter_pages(left_edge=1, right_edge=2 , left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a href="{{url_for('users.user_post', username = username.username ,page=page_num)}}" class="btn  btn-default mb-4 btn-info">{{page_num}}</a>
            {%else%}
              <a href="{{url_for('users.user_post', username=username.username , page=page_num)}}" class="btn btn-default   mb-4  btn-outline-info">{{page_num}}</a>
            {%endif%}
            {%else%}
                ...
        {% endif %}
    {%endfor%}
{%endblock %}